// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HelloWorld_v2.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "HelloWorld_v2.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

HelloWorld_v2::HelloWorld_v2()
{
    // m_index com.eprosima.idl.parser.typecode.PrimitiveTypeCode@f4168b8
    m_index = 0;
    // m_message com.eprosima.idl.parser.typecode.StringTypeCode@3bd94634
    m_message ="";
    // m_value com.eprosima.idl.parser.typecode.PrimitiveTypeCode@58a90037
    m_value = 0.0;

}

HelloWorld_v2::~HelloWorld_v2()
{



}

HelloWorld_v2::HelloWorld_v2(
        const HelloWorld_v2& x)
{
    m_index = x.m_index;
    m_message = x.m_message;
    m_value = x.m_value;
}

HelloWorld_v2::HelloWorld_v2(
        HelloWorld_v2&& x)
{
    m_index = x.m_index;
    m_message = std::move(x.m_message);
    m_value = x.m_value;
}

HelloWorld_v2& HelloWorld_v2::operator =(
        const HelloWorld_v2& x)
{

    m_index = x.m_index;
    m_message = x.m_message;
    m_value = x.m_value;

    return *this;
}

HelloWorld_v2& HelloWorld_v2::operator =(
        HelloWorld_v2&& x)
{

    m_index = x.m_index;
    m_message = std::move(x.m_message);
    m_value = x.m_value;

    return *this;
}

bool HelloWorld_v2::operator ==(
        const HelloWorld_v2& x) const
{

    return (m_index == x.m_index && m_message == x.m_message && m_value == x.m_value);
}

bool HelloWorld_v2::operator !=(
        const HelloWorld_v2& x) const
{
    return !(*this == x);
}

size_t HelloWorld_v2::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t HelloWorld_v2::getCdrSerializedSize(
        const HelloWorld_v2& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.message().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void HelloWorld_v2::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_index;
    scdr << m_message;
    scdr << m_value;

}

void HelloWorld_v2::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_index;
    dcdr >> m_message;
    dcdr >> m_value;
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void HelloWorld_v2::index(
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t HelloWorld_v2::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& HelloWorld_v2::index()
{
    return m_index;
}

/*!
 * @brief This function copies the value in member message
 * @param _message New value to be copied in member message
 */
void HelloWorld_v2::message(
        const std::string& _message)
{
    m_message = _message;
}

/*!
 * @brief This function moves the value in member message
 * @param _message New value to be moved in member message
 */
void HelloWorld_v2::message(
        std::string&& _message)
{
    m_message = std::move(_message);
}

/*!
 * @brief This function returns a constant reference to member message
 * @return Constant reference to member message
 */
const std::string& HelloWorld_v2::message() const
{
    return m_message;
}

/*!
 * @brief This function returns a reference to member message
 * @return Reference to member message
 */
std::string& HelloWorld_v2::message()
{
    return m_message;
}
/*!
 * @brief This function sets a value in member value
 * @param _value New value for member value
 */
void HelloWorld_v2::value(
        float _value)
{
    m_value = _value;
}

/*!
 * @brief This function returns the value of member value
 * @return Value of member value
 */
float HelloWorld_v2::value() const
{
    return m_value;
}

/*!
 * @brief This function returns a reference to member value
 * @return Reference to member value
 */
float& HelloWorld_v2::value()
{
    return m_value;
}


size_t HelloWorld_v2::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;






    return current_align;
}

bool HelloWorld_v2::isKeyDefined()
{
    return false;
}

void HelloWorld_v2::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
       
}
